[package]
name = "slyce"
edition = "2024.beta"
version = "1.0.0"
license = "MIT"
authors = ["Slyce Protocol"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
slyce = "0x0"
