export const transactions = [
  {
    id: 1,
    name: "Emma Richardson",
    amount: 75.5,
    date: "19 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=emma",
  },
  {
    id: 2,
    name: "Savory Bites Bistro",
    amount: -55.5,
    date: "19 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=sun",
  },
  {
    id: 3,
    name: "Daniel Carter",
    amount: 42.3,
    date: "18 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=daniel",
  },
  {
    id: 4,
    name: "Sun Park",
    amount: -120.0,
    date: "17 Aug 2024",
    category: "Rentals",
    image: "https://i.pravatar.cc/150?u=sun",
  },
  {
    id: 5,
    name: "Urban Services Hub",
    amount: -65.0,
    type: "negative",
    date: "17 Aug 2024",
    category: "Printing",
    image: "https://i.pravatar.cc/150?u=emma",
  },
  {
    id: 6,
    name: "Crypto Swap",
    amount: 150.0,
    date: "16 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=crypto",
  },
  {
    id: 7,
    name: "Coffee House",
    amount: -4.5,
    date: "16 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=coffee",
  },
  {
    id: 8,
    name: "Gas Station",
    amount: -45.0,
    date: "15 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=gas",
  },
  {
    id: 9,
    name: "Freelance Design",
    amount: 500.0,
    date: "15 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=design",
  },
  {
    id: 10,
    name: "Hosting Provider",
    amount: -15.0,
    date: "14 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=hosting",
  },
  {
    id: 11,
    name: "Emma Richardson",
    amount: 25.0,
    date: "13 Aug 2024",
    category: "General",
    image: "https://i.pravatar.cc/150?u=emma",
  },
  {
    id: 12,
    name: "Steam Games",
    amount: -59.99,
    date: "12 Aug 2024",
    category: "Entertainment",
    image: "https://i.pravatar.cc/150?u=steam",
  },
];

export const tokens = [
  {
    id: 1,
    symbol: "SUI",
    name: "Sui",
    fiatValue: 15.0,
    amount: 1000,
    iconUrl: "https://cryptologos.cc/logos/sui-sui-logo.png",
    iconFallback:
      "https://raw.githubusercontent.com/sui-foundation/sui/main/docs/images/sui-icon-gradient.png",
  },
  {
    id: 2,
    symbol: "USDC",
    name: "USDC",
    fiatValue: 15.0,
    amount: 1000,
    iconUrl: "https://cryptologos.cc/logos/usd-coin-usdc-logo.png",
    iconFallback:
      "https://raw.githubusercontent.com/centrehq/centre-token-icons/main/trc20/usdc.png",
  },
  {
    id: 3,
    symbol: "BTC",
    name: "BTC",
    fiatValue: 15.0,
    amount: 2000,
    iconUrl: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
    iconFallback:
      "https://raw.githubusercontent.com/bitcoin/bitcoin/master/share/pixmaps/bitcoin.png",
  },
];

export const savingsPots = [
  {
    id: "1",
    title: "Savings",
    totalReceived: 159.0,
    confirmedCollaborators: 3,
    totalCollaborators: 4,
  },
  {
    id: "2",
    title: "Holiday Trip",
    totalReceived: 540.5,
    confirmedCollaborators: 5,
    totalCollaborators: 5,
  },
  {
    id: "3",
    title: "New Laptop",
    totalReceived: 230.0,
    confirmedCollaborators: 2,
    totalCollaborators: 6,
  },
  {
    id: "4",
    title: "Emergency Fund",
    totalReceived: 1200.75,
    confirmedCollaborators: 4,
    totalCollaborators: 4,
  },
  {
    id: "5",
    title: "Birthday Party",
    totalReceived: 85.0,
    confirmedCollaborators: 1,
    totalCollaborators: 8,
  },
  {
    id: "6",
    title: "Gadgets Upgrade",
    totalReceived: 350.0,
    confirmedCollaborators: 3,
    totalCollaborators: 5,
  },
  {
    id: "7",
    title: "Office Setup",
    totalReceived: 450.0,
    confirmedCollaborators: 2,
    totalCollaborators: 3,
  },
  {
    id: "8",
    title: "Team Outing",
    totalReceived: 180.0,
    confirmedCollaborators: 4,
    totalCollaborators: 6,
  },
  {
    id: "9",
    title: "Marketing Campaign",
    totalReceived: 900.0,
    confirmedCollaborators: 5,
    totalCollaborators: 5,
  },
  {
    id: "10",
    title: "Domain Renewal",
    totalReceived: 15.0,
    confirmedCollaborators: 1,
    totalCollaborators: 2,
  },
];
